version: "3"
services:
  site1:
    image: nginx:alpine
    ports:
      - "8001:80"
    volumes:
      - ./site1:/usr/share/nginx/html

  site2:
    image: nginx:alpine
    ports:
      - "9000:80"
    volumes:
      - ./site2:/usr/share/nginx/html
